apiVersion: batch/v1
kind: Job
metadata:
  name: execution-environments-env-global-models-1
spec:
  template:
    spec:
      containers:
        - name: hello
          image: busybox
          command: ["echo", "Hello from the job"]
      restartPolicy: Never
  backoffLimit: 2
