apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "job-runner.fullname" . }}
spec:
  template:
    spec:
      containers:
        - name: hello
          image: busybox
          command: ["echo", "Hello from the job"]
      restartPolicy: Never
  backoffLimit: 2
